---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentication-system-authelia
  namespace: flux-system
spec:
  path: ./cluster/apps/authentication-system/authelia/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: networking-system-traefik
    - name: default-postgrescluster
    - name: default-redis
