# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:+YBqTgE9DR9KLijiR+An9zw=,iv:OVzabVWi5vC7qvqg/vA0Jjv3oiZwZaCU6yc+S8uPojk=,tag:N5Fgm4g98XLqGmxAyTgPFg==,type:str]
    SECRET_DOMAIN_1: ENC[AES256_GCM,data:/qBO5cjri9YNBYf/38G5,iv:uoiMyrZ4Noc2sCdbKpDgEnHuxg/2OH9IAmvLBshHDmc=,tag:fqo8cU5vOf67q2G3el3JAg==,type:str]
    SECRET_DOMAIN_2: ENC[AES256_GCM,data:j2hU5aW1E0WSgLGtcahWJg==,iv:4RmHhvXkuRZgF6c78ohP3KmbppG2XRzYKu75kmUSWzQ=,tag:+i2mf3YGBHCN8QbfM3Y/Bg==,type:str]
    SECRET_EMAIL_0: ENC[AES256_GCM,data:5ZcvPvWK7ILYtsZn2TPRBLc4aXtU,iv:fRaWGwAa6DteYv94mw43u9ZyiJSk8Did9UZmYQhVOPM=,tag:dzQgJEnLCdslU6PauA7l7g==,type:str]
    SECRET_AUTHELIA_PASSWORD_0: ENC[AES256_GCM,data:dPdEe4Rfr4HZzgT01G7M4K+pV/EPuhC0740245rP6IR38cKbTRWmHwriuMsXkk/bvO6q6qZDvaA0PiYRZpdzgNxT4rPlZz/v2CeJamTernwx0wRKkNF+6Lu//04jubvu1QCr,iv:uTSqP00/BUlsZTOh+aO9XnswIH6LfvVTD2k/svaJ22Q=,tag:S06cnfVa7J5eqj0iTYiUGA==,type:str]
    SECRET_PGO_BACKUP_S3_BUCKET: ENC[AES256_GCM,data:252yylSasvKrAey+BMs=,iv:tNoVXBym/Q4mXfyK4yEisq7HLBK1PHZ5Di4Seone+sU=,tag:PkuNlkzkH4VQOu3QyyiCtQ==,type:str]
    SECRET_PGO_BACKUP_S3_ENDPOINT: ENC[AES256_GCM,data:SY8oYJg5s4HHw1+wQMyzOLKT7ZlG7GPGrHJshGPV,iv:bRy2IB+K2TZ1nu53aHcGnZN/Y1LF3S4ZSiuQs8DboKE=,tag:9m2glHV2emikHSeXwBAitQ==,type:str]
    SECRET_PGO_BACKUP_S3_REGION: ENC[AES256_GCM,data:x0DaAYDUZAc48ew=,iv:lMYdW17T6OVWJlKJG156Za+WyGPr7rpuGq6ApFi2egQ=,tag:69zD9X/hyGLZOfW6/6w5IQ==,type:str]
    SECRET_DISCORD_GATUS_WH_URL: ENC[AES256_GCM,data:UD1SYl4ok6uKBS3OCaT6TDK+rXwBuvILixJ5QWgHb9+T/ZJtnQK+5Kbx6Pa4KFAEjBOwY6NsuMQkYyEcYysSr31q3vuSJJ83HKH4L3hScW24J8U7SjMoNZhY/XU0BZ1elJrJzMKufz+uwk1botP3v6ZEfI5+ZIdY,iv:LJtRHHvC9heD8V13WbJ2TAjr0wvNGy/jsBhZyadLLew=,tag:zyjbEnwyvWFRH15eao8vYg==,type:str]
    SECRET_DISCORD_PROMETHEUS_WH_URL: ENC[AES256_GCM,data:tJv0odj794BF37ffgz+sjZTlfpqBzVKIBXu4xfq+GL356h9lpAXZ9LFluTTF/amXbyhjY8GpaWu74DEIaFRp7YF6xEOWaGdzDUT9HYJvIEGIksdDvi9YxzwgG3SGU1lCLr2E0+JABsNVCF9EEq3JAajxtK4NdFIh,iv:KSvxoonovcsSyq2Ow1FZv4Q7QTtrv3DyGRJZM7ySH4o=,tag:CDl9onGd7z0jxpKmwEWHSQ==,type:str]
    SECRET_OMADA_CONTROLLER_ID: ENC[AES256_GCM,data:5nONqV7r62gkhdUcmJcLQzRKjuTxaC+oOj6mL9kNW3A=,iv:i4yUeaPKtjgrXqDAmpGLn637un0W/7T6pHPNjYwmNic=,tag:Oq3ji7PNWPdy2q+M5t1mJw==,type:str]
    SECRET_OIDC_PROXMOX_CLIENT_SECRET: ENC[AES256_GCM,data:V1HSFYiYrNL3v5vr3/omfUSYT87gImpmpuGkWExdqp8P8vZmcVjfOO3LrHIUCowxh2k98sMp2qQQ3gYmidj9FDe3Qo6g0prP,iv:MbBtOL0Nsj5Dptw4kvHJXnWtLEQDEhlP2WGWpzn6WWM=,tag:GLIEZnBYjSXF5B/3kOH9iw==,type:str]
    SECRET_OIDC_MINIO_CLIENT_SECRET: ENC[AES256_GCM,data:PB0wVuFbwV4bLNzK5Jy5VGUFmt9bIVnUiYntW8ONf0uqOyikQSAiFzSrh6tTLEAfyhrWnYhfnHvDf+XsrWGhAajsRG7hCkqN,iv:qfjnaWQxmirUkjd/IoodnPJ0NJxB6fkr8GEkhjuX3AI=,tag:tIvLpPSbbdOEpau02QzjPg==,type:str]
    SECRET_OIDC_NEXTCLOUD_CLIENT_SECRET: ENC[AES256_GCM,data:BXeCuIQ2TY6tQsBaqX38B8oyy5H56ZqKoYboiXRhIJrqHAA/FggAxwu8LxdrxiD7l9QVJaFIgwjjMHsB4DnqsLYU3vfSauCf,iv:nWYIX53OnMN9QQtxkvVjAsZmMAcgmlf3DeMH3bB8VkY=,tag:FvTDQPSfXTatqF2N7eevOA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/rji6RnTYGNhXg2a55HmEQ==,iv:9jHMdBeoC6A6878s23ZdPF33odgSheWWYrmg9tl1e50=,tag:DuauRqTzKBcUjHh3ewmvAw==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:mG3fw5aX1rtQoIAIq3FKES5DcWcRMXMXxAE0CBG/+V8=,iv:u6lxldKXd+pqm3eYAMqh4VWh27sSOPaBcwJjdWI2b1Y=,tag:cWuBwN4QmM/OQOSX2sa+hQ==,type:str]
    SECRET_RESTIC_REPOSITORY_S3: ENC[AES256_GCM,data:fT2Fzg/5oDhXhG7Tsc/MPQhWiafN/N1uEfF6aJHMpKrSppzcY6Ujx0EE54AYPpg6HJcE4CAsYcQk89UC5tz/Sw==,iv:5TJuADV2zckVzI3C3lhENFUyHD+BtnC1GVovqLkqMN4=,tag:CI9XQzCpIDMOmk0JxeMXnw==,type:str]
    SECRET_RESTIC_PASSWORD_S3: ENC[AES256_GCM,data:hrDYtB0sPvNCuYwGWf+s8Q==,iv:JrP4bWFzVk8eUgLEUyfnMmOvreH6uirRcdf8u9Y85Dg=,tag:yd6BtylhK2UwFZ5nVivVOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYlZHdVlLNUFzdmNHY21i
            OGxvNVBka3M1NGV5OWNPM2pYK0JhSGxhTXo0CmgvQWp3a25icnZncDU4UHlGaEJL
            YklRZXFtWjA3VlNOZzRxeUFodU5HWWcKLS0tIFpBSEozRTRXM2ROZmxsS1FmQUNQ
            WWxDelZkZmVPOFZjbGk0MWRCMjhFQ1EKrb2ZRSTsK6akr+lqoNlKm8erdCZWFJNz
            mWhrazBRwpy/WAzNw2wvm6tXVYPLX/TtXIMtTQUPEAxJ6CU0dDnQlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T06:50:48Z"
    mac: ENC[AES256_GCM,data:aiCwngosZ61Bd9Ji7mLKF7YQcDJpZNZM4SGENyv78pyRmeRwTLe431s/5ZSZfC7DMFPBII6K6RMa3efvI/axSGUBVvHiZOW7Eb1EkZLSpH0p4CjW0GBnoSblGsyIv0hT2caHAUcmyDsFxSzhs8jXsBODFiH39F6tav6yK1qLyl8=,iv:dX87Tf7x2oXqZAq39c93waRqMCXHeQaNfbRaYZUfT+8=,tag:BnLzmm/Qf4j7Y7Bo/SRHjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
