apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: default-clusterpolicies
  namespace: flux-system
spec:
  path: ./cluster/apps/default/clusterpolicies/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: false
  wait: true
  dependsOn:
    - name: kyverno-kyverno
