apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name authelia
  namespace: authentication-system
  labels: &labels
    app.kubernetes.io/name: *name
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: *name
          image: ghcr.io/authelia/authelia:4.36.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
          command:
            - sh
            - -c
            - authelia --config /config/configuration.yaml
          ports:
            - name: &port http
              protocol: TCP
              containerPort: 9091
          volumeMounts:
            - name: authelia-config
              mountPath: /config
              readOnly: true
            - name: authelia-secrets
              mountPath: /app/secrets
              readOnly: true
            - name: pgo-cluster-pguser-authelia
              mountPath: /db/secrets
              readOnly: true
          startupProbe:
            httpGet:
              path: /api/health
              port: *port
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /api/health
              port: *port
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /api/health
              port: *port
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /app//secrets/jwt_secret
            - name: AUTHELIA_DUO_API_SECRET_KEY_FILE
              value: /app//secrets/duo_api_secret_key
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /app/secrets/session_secret
            - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
              value: /app/secrets/notifier_smtp_password
            - name: AUTHELIA_SESSION_REDIS_PASSWORD_FILE
              value: /app/secrets/session_redis_password
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
              value: /db/secrets/storage_postgres_password
            - name: AUTHELIA_STORAGE_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-authelia
                  key: host
            - name: AUTHELIA_STORAGE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-authelia
                  key: port
            - name: AUTHELIA_STORAGE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-authelia
                  key: dbname
            - name: AUTHELIA_STORAGE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-authelia
                  key: user
      enableServiceLinks: false
      volumes:
        - name: authelia-config
          configMap:
            name: authelia-configs
        - name: authelia-secrets
          secret:
            secretName: authelia-secrets
            items:
              - key: authelia_jwt_secret
                path: jwt_secret
              - key: authelia_duo_api_secret_key
                path: duo_api_secret_key
              - key: authelia_session_secret
                path: session_secret
              - key: authelia_notifier_smtp_password
                path: notifier_smtp_password
              - key: authelia_session_redis_password
                path: session_redis_password
        - name: pgo-cluster-pguser-authelia
          secret:
            secretName: pgo-cluster-pguser-authelia
            items:
              - key: password
                path: storage_postgres_password
