apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: &name authelia
  namespace: default
  labels:
    app.kubernetes.io/name: *name
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.${SECRET_DOMAIN_0}`)
      services:
        - name: *name
          port: 9091
          namespace: authentication-system
  tls:
    secretName: ${SECRET_CERT_NAME_0}-prod-tls

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: default
  labels:
    app.kubernetes.io/name: authelia
spec:
  forwardAuth:
    address: http://authelia.authentication-system.svc.cluster.local:9091/api/verify?rd=https://auth.${SECRET_DOMAIN_0}
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
