apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authentication-system
  labels:
    app.kubernetes.io/name: authelia
spec:
  selector:
    app.kubernetes.io/name: authelia
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: http
  type: ClusterIP
