apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/weaveworks/kured/releases/download/1.9.0/kured-1.8.2-dockerhub.yaml
patches:
  - path: command-flags-patch.yaml
