apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO: Fix this soon
  - https://github.com/weaveworks/kured/releases/download/1.8.2/kured-1.8.2-dockerhub.yaml
patches:
  - path: command-flags-patch.yaml
