---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nextcloud.${SECRET_DOMAIN_2}`)
      middlewares:
        - name: secure-headers
        - name: nextcloud-redirect-1
        - name: nextcloud-redirect-2
      services:
        - name: nextcloud
          port: 8080
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_2//./-}-prod-tls
