---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/middleware_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect-1
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(card|cal)dav"
    replacement: "https://$1/remote.php/dav/"

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/middleware_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect-2
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "^https?://([^/]*)/.well-known/(webfinger|nodeinfo)$"
    replacement: "https://$1/index.php/.well-known/$2"
