---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: secure-headers
      services:
        - name: homeassistant
          port: 8123
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
