---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: alertmanager
spec:
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: FluxInstance
      name: "*"
    - kind: OCIRepository
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
  suspend: false
