apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
    spec:
      initContainers:
        - name: wait-database
          image: alpine:3.15.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-nextcloud
                  key: host
        - name: wait-redis
          image: alpine:3.15.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $REDIS_HOST:$REDIS_HOST_PORT;
              do echo "Waiting for Redis";
              done
          envFrom:
            - secretRef:
                name: nextcloud-secrets
        - name: init-permission
          image: nginx:1.21-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              chown -R 82:82 /data &&
              chmod -R 750 /data
          volumeMounts:
            - name: nextcloud-data
              mountPath: /data
      containers:
        - name: nextcloud
          image: nextcloud:23.0.3-fpm-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - name: nextcloud-config
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/data
          envFrom:
            - secretRef:
                name: nextcloud-secrets
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-nextcloud
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-nextcloud
                  key: user
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-nextcloud
                  key: host
        - name: nextcloud-cron
          image: nextcloud:23.0.3-fpm-alpine
          imagePullPolicy: IfNotPresent
          command:
            - /cron.sh
          volumeMounts:
            - name: nextcloud-config
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/data
        - name: nextcloud-proxy
          image: nginx:1.21-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - name: nextcloud-nginxconfig
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nextcloud-config
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/data
          startupProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: nextcloud.${SECRET_DOMAIN_0}
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: nextcloud.${SECRET_DOMAIN_0}
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: nextcloud.${SECRET_DOMAIN_0}
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-nginxconfig
          configMap:
            name: nextcloud-nginxconfig
