apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-controller-charts.yaml
  - backube-charts.yaml
  - bjw-s-charts.yaml
  - cilium-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - intel-charts.yaml
  - jetstack-charts.yaml
  - kyverno-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - nextcloud-charts.yaml
  - nfs-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - piraeus-charts.yaml
  - postfinance-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
