apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: gatus
data:
  config.yaml: |
    metrics: true
    endpoints:
      - name: firewall
        group: servers
        url: "icmp://192.168.200.1"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: talos-apiserver
        group: servers
        url: "tcp://192.168.200.20:6443"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: kmaster1
        group: servers
        url: "icmp://192.168.200.21"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: kmaster2
        group: servers
        url: "icmp://192.168.200.22"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: kmaster3
        group: servers
        url: "icmp://192.168.200.23"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: OMV
        group: servers
        url: "icmp://192.168.200.31"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: redis
        group: backend-services
        url: "tcp://redis.default:6379"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: website
        group: frontend-services
        url: "https://${SECRET_DOMAIN_1}"
        interval: 30s
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
      - name: homeassistant
        group: frontend-services
        url: "tcp://homeassistant.default:8123"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: zigbee2mqtt
        group: frontend-services
        url: "tcp://zigbee2mqtt.default:8080"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
      - name: home-dns
        group: frontend-services
        url: 192.168.200.1
        interval: 30s
        dns:
          query-name: "${SECRET_DOMAIN_1}"
          query-type: "A"
        conditions:
          - "[DNS_RCODE] == NOERROR"
          - "[BODY] == ${CONFIG_TRAEFIK_IP}"
        alerts:
          - type: discord
    alerting:
      discord:
        webhook-url: ${SECRET_DISCORD_GATUS_WH_URL}
        default-alert:
          enabled: true
          description: "healthcheck failed"
          send-on-resolved: true
          failure-threshold: 5
          success-threshold: 1
