apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.9.5/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.9.5/deploy/examples/operator.yaml
  - cephcluster-rookCRD.yaml
  - block-storageclass.yaml
  - shared-storageclass.yaml
  - ingress-traefikCRD.yaml
  - grafana-dashboard.yaml
