apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.9.6/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.9.6/deploy/examples/operator.yaml
  - cephcluster-rookCRD.yaml
  - block-storageclass.yaml
  - shared-storageclass.yaml
  - ingress-traefikCRD.yaml
  - grafana-dashboard.yaml
labels:
  - pairs:
      pod-security.kubernetes.io/enforce: privileged
    fields:
      - kind: Namespace
        path: metadata/labels
        create: true
