apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: intel-gpu-plugin
resources:
  - github.com/intel/intel-device-plugins-for-kubernetes/deployments//gpu_plugin?ref=v0.21.0
patchesStrategicMerge:
  - add-nodeselector-patch.yaml
