---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fullykioskbrowser
  labels:
    app.kubernetes.io/name: fullykioskbrowser
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fully.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: secure-headers
        - name: local-only
      services:
        - name: fullykioskbrowser
          port: 2323
          namespace: networking-system
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
