apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - cronjob.yaml
  - deployment.yaml
  - ingress-traefikCRD.yaml
  - pvc.yaml
  - secret.yaml
  - service.yaml
