---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/middleware_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: flux-webhook
spec:
  rateLimit:
    average: 100
    burst: 50
