apiVersion: v1
kind: Endpoints
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
subsets:
  - addresses:
      - ip: 192.168.200.21
      - ip: 192.168.200.22
      - ip: 192.168.200.23
    ports:
      - name: https-metrics
        port: 10257
        protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
subsets:
  - addresses:
      - ip: 192.168.200.21
      - ip: 192.168.200.22
      - ip: 192.168.200.23
    ports:
      - name: https-metrics
        port: 10259
        protocol: TCP
