apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/budimanjojo/kube-prometheus/manifests//deploy?ref=v2.2.3
  - ingress-traefikCRD.yaml
  - endpoints.yaml
  - secret.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: Alertmanager
      name: main
    patch: |-
      - op: add
        path: /spec/configSecret
        value: alertmanager-config
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: ".+"
    patch: |-
      - op: replace
        path: /spec/endpoints/0/interval
        value: 60s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: prometheus-k8s
    patch: |-
      - op: replace
        path: /spec/endpoints/1/interval
        value: 60s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: alertmanager-main
    patch: |-
      - op: replace
        path: /spec/endpoints/1/interval
        value: 60s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: kubelet
    patch: |-
      - op: replace
        path: /spec/endpoints/1/interval
        value: 60s
      - op: replace
        path: /spec/endpoints/2/interval
        value: 60s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: kube-state-metrics
    patch: |-
      - op: replace
        path: /spec/endpoints/1/interval
        value: 60s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: kube-apiserver
    patch: |-
      - op: add
        path: /spec/endpoints/0/metricRelabelings/0
        value:
          action: drop
          regex: apiserver_request_duration_seconds_bucket
          sourceLabels:
            - __name__
      - op: add
        path: /spec/endpoints/0/metricRelabelings/1
        value:
          action: drop
          regex: apiserver_request_slo_duration_seconds_bucket
          sourceLabels:
            - __name__
