apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph-dashboard
  namespace: default
  labels:
    app.kubernetes.io/name: rook-ceph
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`rook.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: local-only@file
      services:
        - name: rook-ceph-mgr-dashboard
          port: 8443
          namespace: rook-ceph
          serversTransport: rook-ceph
  tls:
    secretName: "${SECRET_CERT_NAME_0}-prod-tls"

---

apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: rook-ceph
  namespace: default
  labels:
    app.kubernetes.io/name: rook-ceph
spec:
  insecureSkipVerify: true
