---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`music.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: secure-headers
        - name: authelia
      services:
        - name: lidarr
          port: 8686
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
