apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/budimanjojo/kube-prometheus/manifests//deploy?ref=v2.0.1
  - ingress-traefikCRD.yaml
  - endpoints.yaml
  - service.yaml
