apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kube-controller-manager
  ports:
  - name: https-metrics
    protocol: TCP
    port: 10257
    targetPort: 10257
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kube-scheduler
  ports:
  - name: https-metrics
    protocol: TCP
    port: 10259
    targetPort: 10259
  type: ClusterIP
