---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bazarr.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: dashboard-headers
        - name: authelia
      services:
        - name: bazarr
          port: 6767
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
