---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adminer
  labels:
    app.kubernetes.io/name: adminer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`adminer.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: secure-headers
        - name: local-only
      services:
        - name: adminer
          port: 8080
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
