---
- openmeteo:
    label: Home
    latitude: {{HOMEPAGE_VAR_HOME_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_HOME_LONGITUDE}}
    units: metric
    cache: 5
- openmeteo:
    label: Shop
    latitude: {{HOMEPAGE_VAR_SHOP_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_SHOP_LONGITUDE}}
    units: metric
    cache: 5
