---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    # renovate: depName=prometheus-community/helm-charts datasource=github-tags
    tag: kube-prometheus-stack-39.11.0
  url: https://github.com/prometheus-community/helm-charts.git
  ignore: |
    /*
    !/charts/kube-prometheus-stack/crds
