---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    # renovate: depName=traefik/traefik-helm-chart datasource=github-tags
    tag: v10.19.0
  url: https://github.com/traefik/traefik-helm-chart.git
  ignore: |
    /*
    !/traefik/crds/
