---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: >-
      networking-system-proxmox@kubernetescrd
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8006
      targetPort: https
  type: ClusterIP
