---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-schemas
  labels:
    app.kubernetes.io/name: kubernetes-schemas
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`schemas.${SECRET_DOMAIN_1}`)
      middlewares:
        - name: secure-headers
      services:
        - name: kubernetes-schemas
          port: 8080
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_1//./-}-prod-tls
