---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ombi
  labels:
    app.kubernetes.io/name: ombi
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ombi.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: dashboard-headers
      services:
        - name: ombi
          port: 3579
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
