apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name traefik
  namespace: ingress-system
  labels: &labels
    app.kubernetes.io/name: *name
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: *name
          image: traefik:v2.6.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 150Mi
          args:
            - --global.checknewversion=true
            - --global.sendanonymoususage=false
            - --entrypoints.http.address=:80/tcp
            - --entrypoints.http.http.redirections.entrypoint.to=https
            - --entrypoints.http.http.redirections.entrypoint.scheme=https
            - --entrypoints.http.http.redirections.entrypoint.permanent=true
            - --entrypoints.http.proxyprotocol.trustedips=127.0.0.1
            - --entrypoints.http.forwardedheaders.trustedips=127.0.0.1/32
            - --entrypoints.https.address=:443/tcp
            - --entrypoints.https.proxyprotocol.trustedips=127.0.0.1
            - --entrypoints.https.forwardedheaders.trustedips=127.0.0.1/32
            - --entrypoints.metrics.address=:9100/tcp
            - --entrypoints.traefik.address=:9000/tcp
            - --providers.providersthrottleduration=2
            - --providers.kubernetescrd=true
            - --providers.kubernetesingress=true
            - --providers.kubernetescrd.allowexternalnameservices=true
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --providers.file.directory=/etc/traefik
            - --api.dashboard=true
            - --api.debug=true
            - --ping=true
            - --ping.entrypoint=traefik
            - --log.level=ERROR
            - --log.filepath=/tmp/traefik.log
            - --log.format=json
            - --accesslog=true
            - --accesslog.format=json
            - --accesslog.filters.statuscodes=200,300-302
            - --accesslog.filters.retryattempts=true
            - --accesslog.filters.minduration=450000ns
            - --accesslog.fields.names.defaultmode=drop
            - --accesslog.fields.names.ClientAddr=keep
            - --accesslog.fields.names.RequestAddr=keep
            - --accesslog.fields.names.RequestMethod=keep
            - --accesslog.fields.names.RequestPath=keep
            - --accesslog.fields.names.RequestCount=keep
            - --accesslog.fields.names.RequestProtocol=keep
            - --accesslog.fields.names.RequestScheme=keep
            - --accesslog.fields.names.RetryAttempts=keep
            - --accesslog.fields.names.RouterName=keep
            - --accesslog.fields.names.Duration=keep
            - --accesslog.fields.headers.defaultmode=keep
            - --accesslog.fields.headers.names.Authorization=drop
            - --metrics.prometheus=true
            - --metrics.prometheus.entrypoint=metrics
            - --experimental.http3=true
          ports:
            - name: &port traefik
              protocol: TCP
              containerPort: 9000
            - name: metrics
              protocol: TCP
              containerPort: 9100
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
          volumeMounts:
            - name: traefik-config
              mountPath: /etc/traefik
            - name: traefik-logs
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /ping
              port: *port
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /ping
              port: *port
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          env:
            - name: TZ
              value: ${CONFIG_TIMEZONE}
      serviceAccountName: traefik
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-configs
        - name: traefik-logs
          emptyDir: {}
