---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system-snapshot-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/snapshot-controller/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system-snapshot-controller-validation
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/snapshot-controller/validation
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: kube-system-snapshot-controller
