apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-nginxconfig
  labels:
    app.kubernetes.io/name: wordpress
data:
  default.conf.template: |-
    server {
      listen 80;
      server_name localhost;
      root /var/www/html;

      index index.php;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      rewrite /wp-admin$ $scheme://$host$uri/ permanent;

      location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
          return 404;
        }

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
      }
    }
