---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: goldilocks
  labels:
    app.kubernetes.io/name: goldilocks
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`goldilocks.${SECRET_DOMAIN_0}`)
      middlewares:
        - name: secure-headers
        - name: local-only
      services:
        - name: goldilocks-dashboard
          port: 80
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
