apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: smarter-device-manager
data:
  conf.yaml: |
    - devicematch: ^snd$
      nummaxdevices: 20
    - devicematch: ^gpiomem$
      nummaxdevices: 40
    - devicematch: ^gpiochip[0-9]*$
      nummaxdevices: 20
    - devicematch: ^hci[0-9]*$
      nummaxdevices: 1
    - devicematch: ^i2c-[0-9]*$
      nummaxdevices: 1
    - devicematch: ^rtc0$
      nummaxdevices: 20
    - devicematch: ^video[0-9]*$
      nummaxdevices: 20
    - devicematch: ^vchiq$
      nummaxdevices: 20
    - devicematch: ^vcsm.*$
      nummaxdevices: 20
    - devicematch: ^ttyUSB[0-9]*$
      nummaxdevices: 1
    - devicematch: ^ttyACM[0-9]*$
      nummaxdevices: 1
    - devicematch: ^ttyTHS[0-9]*$
      nummaxdevices: 1
    - devicematch: ^ttyS[0-9]*$
      nummaxdevices: 1
    - devicematch: nvidia-gpu
      nummaxdevices: 20
