name: Update Flux v2

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * *'

jobs:
  flux-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
    - name: Update Flux V2
      id: update_flux
      run: |
        CLI_VERSION="$(flux -v)"
        VERSION="v${CLI_VERSION#*flux version }"
        flux install --version="${VERSION}" \
          --network-policy=false \
          --export > ./fluxcd/base/flux-system/gotk-components.yaml
        echo "::set-output name=flux_version::$VERSION"
    - name: Create pull request for Flux update
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "flux/update-${{ steps.update_flux.outputs.flux_version }}"
        delete-branch: true
        title: "chore(deps): update flux components to ${{ steps.update_flux.outputs.flux_version }}"
        signoff: false
        committer: Github <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: "chore(deps): update flux components to ${{ steps.update_flux.outputs.flux_version }}"
        body: |
          Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update_flux.outputs.flux_version }}
        labels: flux/update
