---
name: Publish Cloudflare networks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_CLOUDFLARE_NETWORKS_FILE: |-
    cluster/apps/networking-system/ingress-nginx/base/cloudflare-networks.txt

jobs:
  cloudflare-networks:
    name: Cloudflare networks
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Cloudflare networks
        run: |
          cloudflare_networks_file=$(find . -name "cloudflare-networks.txt" -print -quit)
          if [[ -f "${cloudflare_networks_file}" ]]; then
            npx zx ./.github/scripts/cloudflareNetworks.mjs > "${cloudflare_networks_file}"
            exit 0
          fi
          npx zx ./.github/scripts/cloudflareNetworks.mjs > ${{ env.DEFAULT_CLOUDFLARE_NETWORKS_FILE }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: "chore(github-action): update Cloudflare networks"
          commit-message: "chore(github-action): update Cloudflare networks"
          delete-branch: true
          committer: budimanjojo-bot <111944664+budimanjojo-bot[bot]@users.noreply.github.com>
          author: budimanjojo-bot <111944664+budimanjojo-bot[bot]@users.noreply.github.com>
          signoff: true
          body: |
            Update Cloudflare network configmap from https://api.cloudflare.com//client/v4/ips
